function(search_unknown_files)
  file(GLOB files RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} *.*)
  list(REMOVE_ITEM files ${ARGN})
  if(files)
    message(SEND_ERROR "found unknown files: ${files}")
  endif()
endfunction()

function(search_unknown_files_recurse)
  file(GLOB_RECURSE files RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} *.*)
  list(REMOVE_ITEM files ${ARGN})
  if(files)
    message(SEND_ERROR "found unknown files: ${files}")
  endif()
endfunction()

function(search_unknown_files_subdir directory sub_directory)
  file(GLOB files RELATIVE ${CMAKE_CURRENT_SOURCE_DIR}/${directory} ${sub_directory}/*.*)
  list(REMOVE_ITEM files ${ARGN})
  if(files)
    message(SEND_ERROR "found unknown files: ${files}")
  endif()
endfunction()
